version: '3.9'

services:
  frontend-nginx:
    image: nginx:latest # 使用最新版本的Nginx镜像
    container_name: gz_vue_base # 定义容器名称
    restart: unless-stopped # 除非手动停止，否则一直重启
    ports:
      - '8080:80' # 映射容器的80端口到主机的80端口
    volumes:
      - ../dist/:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
    networks:
      - webnet # 将服务连接到名为webnet的网络

networks:
  webnet: # 定义网络
    driver: bridge # 使用桥接网络模式，默认已足够
